### ISSUE TITLE
separate libplacebo_debanding grain by channels

### ISSUE THREAD

**Issue by DonCanjas** [Asd-g/avslibplacebo#1]
Would it be possible to have two different grain params, one for luma and another for chroma? Like neo_f3kdb's `grainy` and `grainc`.

**Comment by Asd-g** [comment]
Yes, its possible. I will remove the current parameter `grain` and will introduce `grainY` and `grainC`.

**Comment by Asd-g** [comment]
You can try 1.1.0.
