### ISSUE TITLE
ewa_lanczos4sharpest not recognized

### ISSUE THREAD

**Issue by tormento** [Asd-g/avslibplacebo#10]
Using

libplacebo_Resample(960,516,filter="ewa_lanczos4sharpest")

gives me the error

![image](https://github.com/Asd-g/avslibplacebo/assets/2351785/bd5cdda2-8288-4aac-a99f-5cf6aac3fa76)

Edit: neither ewa_lanczossharp works. Seems that the new kernels are not recognized. Yes, I updated the correct dll ;)

P.S: Why did you remove so many switches in 1.5.0?

**Comment by Asd-g** [comment]
Make sure you don't have loaded older avs_libplacebo version.

You will encounter error because of the height. A height smaller than 540 will raise error (probably libplacebo regression).

The removed parameters are depreciated/removed in the latest libplacebo API.

**Comment by tormento** [comment]
This is the version that I am currently using:

![image](https://github.com/Asd-g/avslibplacebo/assets/2351785/201ba92b-d944-449e-8618-d2a7cea7e458)

The plugin works perfectly with lanczos or mitchell kernels (and others), at that very same resolution.

**Comment by Asd-g** [comment]
I have no issues - https://images2.imgbox.com/05/44/trlZhl3g_o.png

Are you upscaling?

**Comment by tormento** [comment]
This is wicked.

I am downscaling.

EDIT: I think I have found the issue. I had a older version dug with another name in the predefined AVS+ path.

What the hell. Sorry man. Unfortunately I can't test right now as I still have 18 hours of encoding but I think it's ok.

**Comment by tormento** [comment]
As I thought it was the older version giving me problems.

Anyway, I have tested thoroughly the new resampling filters and ewa_lanczos4sharpest gives me the error

![image](https://github.com/Asd-g/avslibplacebo/assets/2351785/69bd1103-181b-4c9f-b952-b41117447e2e)

while ewa_lanczos and ewa_lanczossharp don't.

I have tested the script, bare minimum with resample only and a grey screen in given as output.

**Comment by Asd-g** [comment]
Already [reported](https://github.com/haasn/libplacebo/issues/217).

Still these filters (ewa family) shouldn't be used for downscaling. There is a list of upscalers/downscalers [here](https://github.com/haasn/libplacebo/blob/master/docs/options.md#scaling).

I will set different default filter for downscaling different than upscaling.
