### ISSUE TITLE
convert SDR to HDR?

### ISSUE THREAD

**Issue by mojie126** [Asd-g/avslibplacebo#11]
Hello, may I ask if this tool can convert SDR to HDR?

**Comment by Asd-g** [comment]
It's not allowed currently but possible.

**Comment by mojie126** [comment]
Looking forward to it very much, there is a Python library that is already very close to the color scheme of HDR
https://github.com/colour-science/colour

**Comment by tormento** [comment]
IMHO the easiest way is to apply a LUT, such as the ones from [FranceBB](https://github.com/FranceBB/LinearTransformation).

**Comment by mojie126** [comment]
It looks very good, but it doesn't seem to support the MaskSubMod() filter function as a video source

**Comment by tormento** [comment]
You can apply the LUT with avslibplacebo.

**Comment by mojie126** [comment]
Your release only has x64, but my VSFilterMod is x86, so it shouldn't match

**Comment by theChaosCoder** [comment]
64bit version of VSFilterMod exists too!

**Comment by Asd-g** [comment]
Keep it open until the feature is added (hopefully within several days).

**Comment by mojie126** [comment]
Looks like you're ready to support SDR conversion to HDR? That's very much anticipated!!!

**Comment by mojie126** [comment]
Also, I can hope to have an x86 version

**Comment by tormento** [comment]
Please, consider to add the possibility to feed 8/10/12 bit video to the tonemap filter and have internal conversion to 16 bit in and original bitdepth out. As I wrote in a previous issue, z.img is so slow.

**Comment by Asd-g** [comment]
Version `1.5.2` can do SDR->HDR.
