### ISSUE TITLE
Processed image slightly shifted and tinted

### ISSUE THREAD

**Issue by tormento** [Asd-g/avslibplacebo#12]
I was looking for a good downsize resolution and I kept the original image and the resized one side by side.

My eyes tell me that the processed image is slightly shifted and the red color is a bit different.

I have tried many times and I find always the same behaviour.

Please look at them and tell me if I am wrong or not.

LoadPlugin("D:\Eseguibili\Media\DGDecNV\DGDecodeNV.dll")
DGSource("M:\In\Inuyasha 7 - The final act 810p ~Dynit\2009_10 7\192.dgi")

![2](https://github.com/Asd-g/avslibplacebo/assets/2351785/bc7c318a-a527-439a-8a05-b8e74b79ff2f)

LoadPlugin("D:\Eseguibili\Media\DGDecNV\DGDecodeNV.dll")
DGSource("M:\In\Inuyasha 7 - The final act 810p ~Dynit\2009_10 7\192.dgi")
libplacebo_Resample(1440,810,filter="mitchell")

![1](https://github.com/Asd-g/avslibplacebo/assets/2351785/387dc024-1800-4191-8060-8785eefcccb5)

LoadPlugin("D:\Eseguibili\Media\DGDecNV\DGDecodeNV.dll")
DGSource("M:\In\Inuyasha 7 - The final act 810p ~Dynit\2009_10 7\192.dgi")
[VideoTek()](https://github.com/FranceBB/VideoTek)

![4](https://github.com/Asd-g/avslibplacebo/assets/2351785/ee8074ac-860f-4392-ade9-86baedff117e)

LoadPlugin("D:\Eseguibili\Media\DGDecNV\DGDecodeNV.dll")
DGSource("M:\In\Inuyasha 7 - The final act 810p ~Dynit\2009_10 7\192.dgi")
libplacebo_Resample(1440,810,filter="mitchell")
VideoTek()

![3](https://github.com/Asd-g/avslibplacebo/assets/2351785/ab7c0c1e-4c10-4693-ad6e-346c6d5a4ef6)

**Comment by Asd-g** [comment]
Compare it to another filter. For example, `libplacebo_Resample(1440,810,filter="mitchell")` vs `z_BicubicResize(1440 ,810, b=1/3.0, c=1/3.0)`.
