### ISSUE TITLE
Hello, I hope to obtain an x86 version. Thank you

### ISSUE THREAD

**Issue by mojie126** [Asd-g/avslibplacebo#13]
Hello, I hope to obtain an x86 version. Thank you

**Comment by Asd-g** [comment]
Do you really use avs+ x86 nowadays?

**Comment by mojie126** [comment]
Yes, I am using the mingw32 environment, which only supports 32-bit applications and DLLs

**Comment by Asd-g** [comment]
Attached 32-bit avs_libplacebo 1.5.2.

[avs_libplacebo.zip](https://github.com/Asd-g/avslibplacebo/files/13764779/avs_libplacebo.zip)

**Comment by mojie126** [comment]
thank you very much
