### ISSUE TITLE
Internal full ↔ limited

### ISSUE THREAD

**Issue by tormento** [Asd-g/avslibplacebo#14]
I want to use an external LUT libplacebo_Tonemap but I can't understand if it accepts both limited and full types, doing internal video conversions.

If not, could you add that feature by GPU?

Thanks.

**Comment by Asd-g** [comment]
Full range is expected.

Your request is for [the libplacebo devs](https://github.com/haasn/libplacebo) (the whole filtering chain is part of libplacebo).

**Comment by tormento** [comment]
Yep, I noticed. Using the correct src_csp and dst_csp gives the expected result.

Thank you.
