### ISSUE TITLE
libplacebo_Resample issue

### ISSUE THREAD

**Issue by tormento** [Asd-g/avslibplacebo#15]
Whenever I try

[DeHalo_Beta_placebo()](https://github.com/DonCanjas/Avisynth-Functions/blob/main/Dehalo_Beta_Package/Dehalo_Beta.avsi)

in a script, I get the error:

libplacebo_Resample: [error] vk->CreateDevice(vk->physd, &dinfo, PL_VK_ALLOC, &vk->dev): VK_ERROR_INITIALIZATION_FAILED (../src/vulkan/context.c:1299)
[fatal] Failed creating logical device!
[fatal] Failed initializing vulkan device

Avslibplacebo works fine as standalone filter on my computer.

Any idea?

**Comment by Asd-g** [comment]
I cannot test it until November.
Meanwhile you can test with the attached script - either you will have error or you will have a messsage `ok xxx`.
1. If you have message `ok xxx` open the script, find the first line that have `return MessageClip...`, delete it and rerun the script.
2. If you have again a message `ok xxx`, repeat 1.
3. Repeat 2 until you have error.

[test.zip](https://github.com/user-attachments/files/17437527/test.zip)

**Comment by tormento** [comment]
I can run it to the bottom.

Perhaps the "ok" image is too little in memory to trigger something.

**Comment by Asd-g** [comment]
Did you get any `ok` image or you get only the error from the first comment?

**Comment by tormento** [comment]
I got all the ok.

**Comment by Asd-g** [comment]
So if you remove all lines with `return MessageClip("ok...)`, the script runs fine?

**Comment by tormento** [comment]
Yes.

**Comment by Asd-g** [comment]
Thanks for testing.

Can you test also the attached `test1.avsi` in the same way?

[test1.zip](https://github.com/user-attachments/files/17476391/test1.zip)

**Comment by Asd-g** [comment]
@tormento, I don't have issues with the following script (non-modified DeHalo_Beta_placebo()):

```
Import("Dehalo_Beta.avsi")

BlankClip(pixel_type="yuv420p16", width=1920*2, Height=1080*2)
DeHalo_Beta_placebo()
```

Do you have issues with this script?

**Comment by tormento** [comment]
I think I've found the issue: it's "simply" a VRAM memory starvation.

Unfortunately GPU related issues are so cryptic in their error messages.

Thanks for all your support!
