### ISSUE TITLE
Is Dolby Vision a colorspace?

### ISSUE THREAD

**Issue by wyup** [Asd-g/avslibplacebo#16]
In [tonemapping options](https://github.com/Asd-g/avslibplacebo?tab=readme-ov-file#tone-mapping):
```
src_csp, dst_csp
Respectively source and output color space.
0: SDR
1: HDR10
2: HLG
3: DOVI
Default: src_csp = 1; dst_csp = 0.
```
How is Dolby Vision a colorspace? I thought it is mostly a propietary tonemapping algorithm for tvs and media players.
AFAIK, movies with Dolby Vision are mostly in Rec.2020 colorspace and PQ, that's to say: HDR10.

**Comment by quietvoid** [comment]
It's not just about tone mapping, it's its own colorspace when we're talking about profile 5.
Because it requires reshaping to become PQ/Rec.2020.

**Comment by wyup** [comment]
So then should I use DOVI colourspace instead of HDR10 with profile 5 upwards for increased precision?
What is exactly DV colorspace: BT.2020 with IPTPQc2/ICTCP representation?
I guess 4k/HDR10 content is mostly mastered in PQ colorspace, hence DV might be in broader Rec.2020.
Does it have to do with FEL 12-bit layer or is independent?

**Comment by quietvoid** [comment]
> So then should I use DOVI colourspace instead of HDR10 with profile 5 upwards for increased precision?

You have to use it for profile 5 or anything you want reshaping processed.

> What is exactly DV colorspace: BT.2020 with IPTPQc2/ICTCP representation?

Yes.

> Does it have to do with FEL 12-bit layer or is independent?

Profile 7 may have reshaping as well, but the EL part is done _after_ reshaping.

**Comment by wyup** [comment]
But in reality, it is not another colorspace. It is BT.2020 with full range and ICtCp representation and cross talk matrix.
But for that to be consistent, the movie should be graded in BT.2020 and normally mastering monitor is PQ, as reported by the HDR10 colorspace metadata.
