### ISSUE TITLE
Clamp=1 blurs output

### ISSUE THREAD

**Issue by Dogway** [Asd-g/avslibplacebo#2]
Some filter strings don't work on _resample, nor _shader:
"box" not working ("nearest" does though)
"haasnsoft" also doesn't work

I also had strange results using "clamp"
`libplacebo_Resample(width()*2,height()*2, filter="ewa_ginseng",radius=6,clamp=1)`
In this case radius=6 is blurrier than radius=3, except when I set clamp to 0.
Basically I wanted to clamp negative values so they don't NaN later on float pipelines.

**Comment by Asd-g** [comment]
About filters I have to update README.md. [This is the correct list](https://github.com/haasn/libplacebo/blob/v4.208.0/src/filters.h#L20-L47).

I will take a look at clamp.

**Comment by Asd-g** [comment]
I updated README.md with the correct resampling filter names.

libplacebo_Resample(width()*2,height()*2, filter="ewa_ginseng",radius=6,clamp=0) is still blurrier than libplacebo_Resample(width()*2,height()*2, filter="ewa_ginseng",radius=3,clamp=0) but not that visibly.
Even libplacebo_Resample(width()*2,height()*2, filter="ewa_ginseng",radius=3,clamp=1) is visibly blurrier than libplacebo_Resample(width()*2,height()*2, filter="ewa_ginseng",radius=3,clamp=0).
Usually you should expect blurrier result with `clamp=1`.

`clamp=1` still can produce negative output values. It clamps only the weights when generating the filter.
You have to manually clamp the output values.

**Comment by Dogway** [comment]
I understand now, only clamps negative lobes(?).
I was waiting for this to upload TransformsPack so will update tomorrow.
Thanks!

**Comment by Asd-g** [comment]
> I understand now, only clamps negative lobes(?).

Yes.
