### ISSUE TITLE
src_width/height in "_Resample" to correct chroma shift

### ISSUE THREAD

**Issue by Dogway** [Asd-g/avslibplacebo#4]
Is it possible to add 'src_width' and 'src_height' args to libplacebo_Resample?
I found myself battling with this since it's needed to correct chroma shift in a manual way.

I presume it's correcting it when fed with YCbCr but it's useful in cases where you want to scale luma and chroma with different kernels, or simply change subsampling while accounting for chroma shift (422 to 420 while scaling).

**Comment by Asd-g** [comment]
You can try 1.1.3.

**Comment by Dogway** [comment]
Thanks! Working great now.
