### ISSUE TITLE
Use of LUTs

### ISSUE THREAD

**Issue by tormento** [Asd-g/avslibplacebo#5]
I saw that LUT can be used in dithering but I am wondering if we are talking of the same LUT such as the ones for PQ to HLG conversion.

Is there a way to use a LUT for that usage, possibily in tetrahedral interpolation?

**Comment by Asd-g** [comment]
> I saw that LUT can be used in dithering but I am wondering if we are talking of the same LUT such as the ones for PQ to HLG conversion.

It's different LUT.

> Is there a way to use a LUT for that usage, possibily in tetrahedral interpolation?

No.
Btw there is [tonemapping](https://github.com/Asd-g/avslibplacebo#tone-mapping) function that can do PQ->HLG.

**Comment by tormento** [comment]
How precise is tonemapping compared to AVS/VSCube and a commercial PQ to HLG LUT?

**Comment by Asd-g** [comment]
When talking about tonemapping, nothing is precise. Just tried it and see.

**Comment by tormento** [comment]
If you are on Doom9 forum, you can see the bad approximation of trilinear functions instead of tethraedral, there are many images, from FranceBB and other guys.

**Comment by Asd-g** [comment]
I talked about tonemapping. It can be done without LUTs.
