### ISSUE TITLE
Tone-mapping target output color space and gamma

### ISSUE THREAD

**Issue by nicko88** [Asd-g/avslibplacebo#8]
Is there a possibility to allow targeting BT.2020 and different gamma curves (i.e 2.2 and 2.4) for HDR to SDR tone-mapping?

My displays support wider color than BT.709, like DCI-P3 and are calibrated to the BT.2020 color space, but they do not support HDR, or have poor HDR support. They are also usually calibrated to either 2.2 gamma or 2.4 gamma.

This is a common thing in projectors for tone-mapping systems like madVR, or a Lumagen video processor box and is often called SDR.2020, where we convert HDR10 PQ to BT.2020 Gamma 2.2 for example.

**Comment by Asd-g** [comment]
You can try the latest version (1.4.1) - `libplacebo_Tonemap(..., dst_prim=6, dst_trc=x, dst_sys=4)`.

**Comment by nicko88** [comment]
Awesome! Thank you for adding all the destination gamuts and tone reproduction curves. 

This makes the filter much more flexible!
