### ISSUE TITLE
Help for compilation?

### ISSUE THREAD

**Issue by erazortt** [Asd-g/avslibplacebo#9]
Hey, I'm having quite some hard time compiling this. Perhaps you could help me out.
I want to compare your computation with DoViBaker and for that I would want to have a debug enabled version.
How does you compiling procedure look like for the whole thing (including the dependencies)?

**Comment by Asd-g** [comment]
Hi.
You need clang-cl/icc for compiling libplacebo. I use [this](https://github.com/zufuliu/llvm-utils) to add clang-cl support for Visual Studio and also the latest release from [here](https://github.com/llvm/llvm-project/releases). But clang-cl shipped with Visual Studio is probably ok.
Installed Vulkan SDK from [here](https://vulkan.lunarg.com/sdk/home#windows).
Clone this repository with the sub modules (git clone --recurse-submodules ....).
Following the instructions from [here](https://github.com/Asd-g/avslibplacebo#building) by replacing `release` with `debug` for the steps and then using the solution from [here](https://github.com/Asd-g/avslibplacebo/tree/main/msvc) (Debug version) should work. You may want change the path to the Vulkan include and lib location (in Visual Studio) in case the Vulkan folder and avslibplacebo aren't next to each other.

**Comment by erazortt** [comment]
Thanks!
